#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --time=00:30:00
#SBATCH --partition=dev_cpuonly
#SBATCH --output=log/job%j.output
#SBATCH --error=log/job%j.error
#SBATCH --job-name=all_flav_ammonia

source /opt/bwhpc/common/devel/miniconda3/etc/profile.d/conda.sh

conda activate dft_data_generation

module load chem/turbomole/7.7.1

export PYTHONPATH=~/dft_data_generation/
export PYTHONPATH=~/dft_data_generation/utils/

python /home/hk-project-aimat2/mt4181/data_generation_dft/create_placeholder_categories.py /home/hk-project-aimat2/mt4181/data_generation_dft/input_files/small_flavours.json /home/hk-project-aimat2/mt4181/data_generation_dft/input_files/Ala_cap_rad.xyz /hkfs/work/workspace/scratch/mt4181-dft/dipeptides_test/categories 2