#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --time=00:30:00
#SBATCH --partition=<partition_name>
#SBATCH --output=log/job%j.output
#SBATCH --error=log/job%j.error
#SBATCH --job-name=<name>

source <conda.sh path>
conda activate dft_data_generation
module load chem/turbomole/7.7.1

export PYTHONPATH=~/dft_data_generation/
export PYTHONPATH=~/dft_data_generation/utils/

python create_placeholder_categories.py \
<flavours.json path> \
<dataset with xyz files path> \
<path to store the results (placeholder categories) in> \
<number of molecules to sample per datatype per flavour> 